#ifndef XNETBASICLIBSTATIC_GLOBAL_H
#define XNETBASICLIBSTATIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XNETBASICLIBSTATIC_LIBRARY)
#  define XNETBASICLIBSTATIC_EXPORT Q_DECL_EXPORT
#else
#  define XNETBASICLIBSTATIC_EXPORT Q_DECL_IMPORT
#endif

#endif // XNETBASICLIBSTATIC_GLOBAL_H
